kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "dsv.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "dsv.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "dsv.fullname" . }}
    namespace: {{ .Release.Namespace }}
