apiVersion: v1
kind: ConfigMap
metadata:
   name: {{ include "dsv.name" . }}-configmap
data:
  REFRESH_TIME: {{ .Values.configmap.refreshTime }}
  DSV_API_URL: {{ .Values.configmap.dsvAPIURL }}
  TENANT: {{ .Values.configmap.tenant }}
  CLIENT_ID: {{ .Values.configmap.clientID }}
  CLIENT_SECRET: {{ .Values.configmap.clientSecret }}
  LOG_LEVEL: {{ .Values.configmap.logLevel }}
  AUTH_TYPE: {{ .Values.configmap.authType }}