---
project_name: dsv-sidecar
dist: .artifacts
env:
  - GITHUB_TOKEN='null' # required to bypass check as this tool integrates heavily with those systems
  - GITLAB_TOKEN=''
  - GITEA_TOKEN=''
  - LOCAL_DEBUGGING=false # set to make this quick and bypass extra effort builds like archiving zip
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download
builds:
  - id: controller
    binary: dsv-controller
    main: cmd/controller/main.go
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos: [linux]
    goarch: [amd64]

  - id: client
    binary: dsv-client
    main: cmd/client/main.go
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos: [linux]
    goarch: [amd64]

archives:
  - id: binary
    format: binary
  - id: replacements
    replacements:
      386: i386
      amd64: x86_64
checksum:
  name_template: checksums.txt
snapshot:
  name_template: '{{ incpatch .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
