---
project_name: dsv-sidecar
dist: .artifacts
env:
  - GITHUB_TOKEN=''
  - GITLAB_TOKEN=''
  - GITEA_TOKEN=''
  - LOCAL_DEBUGGING=false # set to make this quick and bypass extra effort builds like archiving zip
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download
builds:
  - id: controller
    binary: dsv-controller
    main: cmd/controller/main.go
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w
      - -X main.version={{ .Summary }}
      - -X main.commit={{ .FullCommit }}
      - -X main.date={{ .Timestamp }}
      - -X main.builtBy=goreleaser
    goos: [linux]
    goarch: [amd64]

  - id: client
    binary: dsv-client
    main: cmd/client/main.go
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w
      - -X main.version={{ .Summary }}
      - -X main.commit={{ .FullCommit }}
      - -X main.date={{ .Timestamp }}
      - -X main.builtBy=goreleaser
    goos: [linux]
    goarch: [amd64]

archives:
  - id: binary
    format: binary
  - id: replacements
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: checksums.txt
  algorithm: sha256
  disable: false
snapshot:
  name_template: '{{ incpatch .Version }}-next'
changelog:
  skip: false
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'CI & Chore'
      regexp: "^.*(fix|chore|build)[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^style:'
sboms:
  - artifacts: binary
    documents:
      - '${artifact}.spdx.sbom'
dockers:
  - id: docker-publish
    goos: linux
    image_templates:
      - '{{ if index .Env "DOCKER_ORG" }}{{ .Env.DOCKER_ORG }}/{{ .ProjectName }}:{{ .Tag }}{{ end }}'
      - '{{ if index .Env "DOCKER_ORG" }}{{ .Env.DOCKER_ORG }}/{{ .ProjectName }}:latest{{ end }}'
    skip_push: false
    dockerfile: ./docker/Dockerfile.distroless
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.version={{.Version}}
      # - --label=org.opencontainers.image.version="{{ .Tag }}"
  # local builds
