FROM golang:latest AS build-env
ARG LD_FLAGS
WORKDIR /go/src/github.com/DelineaXPM/dsv-k8s-sidecar
COPY . .
RUN go version
RUN GO111MODULE=on CGO_ENABLED=0 go test ./...
RUN GO111MODULE=on CGO_ENABLED=0 go build -ldflags "$LD_FLAGS" cmd/controller/main.go

FROM busybox:latest
LABEL maintainer="thycotic.com"
ENV PORT 3000
EXPOSE 3000
ENV TENANT=""
ENV CLIENT_ID=""
ENV CLIENT_SECRET=""
ENV REFRESH_TIME="15m"
ENV PORT=":3000"
ENV LOG_LEVEL=""
ENV AUTH_TYPE=""

COPY --from=build-env /go/src/github.com/DelineaXPM/dsv-k8s-sidecar /
COPY --from=build-env /usr/share/ca-certificates/mozilla/Amazon_Root_CA_*.crt /etc/ssl/certs/
CMD /main -tenant $TENANT -client-id $CLIENT_ID -client-secret $CLIENT_SECRET -port $PORT -log-level $LOG_LEVEL -auth-type $AUTH_TYPE
