---
apiVersion: v2
name: dsv-k8s-sidecar
description: |
  A Helm chart for the Delinea DevOps Secrets Vault (DSV) k8 sidecar.
  This is installed per service as a sidecar.

  Install directly with helm via:

  ```shell
  NAMESPACE='dsv'
  IMAGE_REPOSITORY='docker.io/delineaxpm/dsv-k8s-sidecar'

  helm install
      --namespace $NAMESPACE
      --create-namespace \
      --atomic \
      --timeout "5m" \
      --set image.repository=${IMAGE_REPOSITORY} \
      dsv-k8s-sidecar ./charts/dsv-k8s-sidecar
  ```

icon: https://delinea.com/hubfs/Delinea/icons/product%20icons/delinea-icon-platform.svg
keywords:
  - Delinea
  - DevOps
  - DSV
  - secrets
  - vault
type: application
# WARNING: Version should be bumped by changie, not manually.
version: v1.0.1
appVersion: latest
maintainers:
  - name: Delinea DSV Team
