# https://goreleaser.com/customization/docker/?h=scrat#how-it-works
# trunk-ignore(hadolint/DL3007)
FROM cgr.dev/chainguard/static:latest
COPY dsv-k8s-sidecar /app/dsv-k8s-sidecar
ENTRYPOINT [ "/app/dsv-k8s-sidecar" ]
