---
# Default values for the Delina DevOps Secrets Vault (DSV) Secrets sidecar.

# -- replicate count
# @default - 1
replicaCount: 1

image:
  repository: docker.io/delineaxpm/dsv-k8s-controller
  pullPolicy: Always
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: latest

nameOverride: ''
fullnameOverride: ''

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  brokergrpc:
    port: 80
    targetPort: 3000
  brokerauth:
    tcpport: 80
    tcptargetPort: 8080
    tlsport: 443
    tlstargetPort: 443


resources: {}
# limits:
#   cpu: 500m
#   memory: 512Mi
# requests:
#   cpu: 500m
#   memory: 512Mi

configmap:
  refreshTime: 5m
  dsvAPIURL: https://%s.devbambe.com/v1
  tenant: mal
  clientID: fhgfghfhgh656hgfhjDSDSD5456456465456
  clientSecret: GHFGHFGHF6GHFHGvmv7567nvhnnrhgf65
  logLevel: debug
  authType: client_credentials

strategy:
  type: RollingUpdate
  rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
