---
# Default values for the Delina DevOps Secrets Vault (DSV) Secrets sidecar.

# -- replicate count
# @default - 1
replicaCount: 1


## User's service image 
image:
  repository: 
  pullPolicy: Always
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ''

nameOverride: ''
fullnameOverride: ''

podAnnotations: 
    dsv: mal

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


resources: {}
# limits:
#   cpu: 500m
#   memory: 512Mi
# requests:
#   cpu: 500m
#   memory: 512Mi

env:
  refreshTime: 5s
  secrets: resources/us-east-1/server1
  logLevel: debug
   # Required if broker is in different namespace
  brokerNamespace: ''

sidecarimage:
  repository: dsv-k8s-client
  tag: latest
  pullPolicy: IfNotPresent
