---
name: lint
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
permissions:
  pull-requests: write
  contents: read
  checks: write
jobs:
  lint:
    uses: delineaxpm/github-workflows/.github/workflows/lint.yml@main
    secrets: inherit
